apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - namespace.yaml
  - ../../base/frontend
patches:
  - path: patches/frontend-patch.yaml
replicas:
  - name: frontend
    count: 3
