apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: kube-system # Deploy to existing kube-system
  install:
    createNamespace: false # kube-system already exists
  chart:
    spec:
      chart: metrics-server
      version: "3.11.x"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  values:
    args:
      - --cert-dir=/tmp
      - --secure-port=10250
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      - --kubelet-use-node-status-port
      - --metric-resolution=15s
      - --kubelet-insecure-tls
