apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  timeout: 15m # Increase timeout from default 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.9.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  install:
    createNamespace: true
    remediation:
      retries: 3
    # Install CRDs separately to avoid timeout
    skipCRDs: false
    timeout: 15m # Increase install timeout
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  # Start with minimal values - add more later
  values:
    # Reduce initial resource requirements
    defaultRules:
      create: false # Skip rules initially

    grafana:
      enabled: true
      adminPassword: "changeme123!"
      persistence:
        enabled: false # Disable initially
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi

    prometheus:
      enabled: true
      prometheusSpec:
        retention: 7d # Reduce retention
        resources:
          requests:
            memory: 200Mi
            cpu: 50m
          limits:
            memory: 500Mi
            cpu: 200m
        # Disable persistent storage initially
        storageSpec: {}

    alertmanager:
      enabled: false # Disable initially

    # Disable most exporters initially
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: false
    prometheusOperator:
      enabled: true
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi

    # Disable other components
    kubeApiServer:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kubeEtcd:
      enabled: false
    coreDns:
      enabled: false
